def function_this_exception(value):
    return 1 / value


# print(function_this_exception(0))
